### ISSUE TITLE
gzip: stdin: not in gzip format tar: Child returned status 1 tar: Error is not recoverable: exiting now

### ISSUE THREAD

**Issue by ShahriarKh** [FusionAuth/fusionauth-install#11]
I installed FusionAuth via:
`sh -c "curl -fsSL https://raw.githubusercontent.com/FusionAuth/fusionauth-install/master/install.sh | sh -s - -z -s"`

However, when I try to run the `bin/startup.sh`, I get this:
```  
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   688  100   688    0     0   2166      0 --:--:-- --:--:-- --:--:--  2170

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```
What's the problem?
(I'm not familiar with linux and am just trying to set-up FusionAuth in a share Node.js host)

**Comment by mooreds** [comment]
Probably related to https://github.com/FusionAuth/fusionauth-install/issues/10 Can you try adding `-L` in `startup.sh`?

**Comment by ShahriarKh** [comment]
How & where should I do that?
I tried `bin/startup.sh -L` but it outputs the same thing as before.

**Comment by mooreds** [comment]
Edit bin/startup.sh and wherever you see `curl`, change it to `curl -L`.

**Comment by ShahriarKh** [comment]
It is working now. Thanks a bunch!
