### ISSUE TITLE
Default to only down app bundle and default to db search engine

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-install#3]
Beginning in version 1.16.0, db search will be default and we can modify the fast path to only download the search bundle if requested. 

Tasks
- [x] add flag to install scripts to ask for search, default will be no
- [ ] update fast path install guide in doc
- [x] update readme here to provide examples of how to call it
- [ ] review download page on brochure site to see if it needs changes

**Comment by tyduptyler13** [comment]
Using latest released bundle the following installs do not work without search:
* deb
* rpm
* zip

Installing just the deb/rpm/zip results in maintenance mode asking for your search engine url and won't let me continue.

![image](https://user-images.githubusercontent.com/1331209/80517700-b1ad6880-8942-11ea-86e9-eb629c231a4e.png)

**Comment by tyduptyler13** [comment]
Checked what our metrics url says is the latest version, it reports 1.15.8. Probably why it doesn't work. So disregard for now.

**Comment by tyduptyler13** [comment]
Running into issues when installing 1.16.0 with search for some reason. (It works fine without search)

```
Apr 28, 2020 6:57:17.766 PM ERROR org.primeframework.mvc.guice.GuiceBootstrap - 

===================================================================================================

  Unable to start the server. Here's why: 


[Error injecting constructor, org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: java.sql.SQLException: Field 'runtime_mode' doesn't have a default value
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: INSERT INTO nodes (id, insert_instant, last_checkin_instant, url) VALUES (?, ?, ?, ?)     ON DUPLICATE KEY UPDATE last_checkin_instant = VALUES(last_checkin_instant), url = VALUES(url)
### Cause: java.sql.SQLException: Field 'runtime_mode' doesn't have a default value] 
        -> [class org.apache.ibatis.exceptions.PersistenceException] 
### Error updating database.  Cause: java.sql.SQLException: Field 'runtime_mode' doesn't have a default value
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: INSERT INTO nodes (id, insert_instant, last_checkin_instant, url) VALUES (?, ?, ?, ?)     ON DUPLICATE KEY UPDATE last_checkin_instant = VALUES(last_checkin_instant), url = VALUES(url)
### Cause: java.sql.SQLException: Field 'runtime_mode' doesn't have a default value

===================================================================================================
```

**Comment by tyduptyler13** [comment]
I figure we don't want to explode with an obscure exception if we start with search enabled and a fresh install so I included @trex

**Comment by tyduptyler13** [comment]
Nevermind, figured it out.

**Comment by tyduptyler13** [comment]
Finished adding and testing but the one flaw is that windows won't automatically use the elasticsearch if its downloaded. It seems to jump to database mode and stay there. I wonder if the port isn't getting bound quickly enough or something.

**Comment by tyduptyler13** [comment]
Waiting for the release of `1.16.0` to update doc and brochure. At that point we can merge the branch.
