### ISSUE TITLE
404

### ISSUE THREAD

**Issue by klemens-morgenstern** [FusionAuth/fusionauth-install#5]
When I trying to execue the scripts (windows and linux), I am getting a 404 error. Same happens when I try to download directly from the website.

```powershell
PS C:\develop\fusionauth> iex (new-object net.webclient).downloadstring('https://raw.githubusercontent.com/FusionAuth/fusionauth-install/master/install.ps1')
Install FusionAuth version 1.0.0
Installing zip packages
Downloading archive, destination C:\develop\fusionauth\fusionauth
Start-BitsTransfer : HTTP-Status 404: Die angeforderte URL ist auf diesem Server nicht vorhanden.
In Zeile:20 Zeichen:9
+         Start-BitsTransfer -Source $uri -Destination $tempFile
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-BitsTransfer], Exception
    + FullyQualifiedErrorId : StartBitsTransferCOMException,Microsoft.BackgroundIntelligentTransfer.Management.NewBitsTransferCommand

PS C:\develop\fusionauth>
```

**Comment by mooreds** [comment]
I was able to view the `https://raw.githubusercontent.com/FusionAuth/fusionauth-install/master/install.ps1` from my browser. Are you able to access other raw GitHub urls?

For example: https://raw.githubusercontent.com/github/training-kit/master/README.md

or https://raw.githubusercontent.com/github/ghfw-build-extra/master/download-stats.sh which is a shell script?

If not, it may be a firewall or permissions issue. If you can download the other scripts but not the FusionAuth ones, please let us know so we can do additional troubleshooting.

**Comment by klemens-morgenstern** [comment]
Oh sorry, I can of course download the script, but whatever it's trying to download to doesn't work. Well didn't, I think something was off about your website, it only showed 1.0.0. [here](https://fusionauth.io/direct-download)

Guess it works now, so nevermind.

Thanks!
